### ISSUE TITLE
Jumper Control Center safe mode

### ISSUE THREAD

**Issue by 19770819lyl** [neoighodaro/switcher-issues#10]
Hello, I buy your plug-in Jumper. After installation, the operation control center will enter safe mode. All plug-ins except Jumper are still problematic. The mobile phone is 13PM, the system version IOS15.0.2, dopamine jailbreak, now apply for a refund, I hope you can deal with it in your busy schedule, thank you.
![Uploading 26AAE89F-9469-464F-A583-2C6E715ADBC5.png…]()

**Comment by neoighodaro** [comment]
can you send me your order id?
