### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Bmxvu** [neoighodaro/switcher-issues#14]
My phone keeps going into safemode and I’m unable to use the tweak please help posted below is the crash log
[Jumper Crash Log.txt](https://github.com/user-attachments/files/15945727/Jumper.Crash.Log.txt)

**Comment by neoighodaro** [comment]
Hey thanks for reporting, since for now its not in active development, IF you purchased Jumper recently, please send me your Havoc order ID portion.influx-0j@icloud.com, I'll send you a refund. If its not a recent purchase, I may not be able to do anything about it for now.
