### ISSUE TITLE
Jumper 2.0.2 breaks tweak 'QuickCC'

### ISSUE THREAD

**Issue by v6boss** [neoighodaro/switcher-issues#2]
After updating Jumper to 2.0.2 it was noticed that QuickCC no longer works as expected. The selection screen where specific wifi networks or bluetooth devices does not pop up any more.
Jumper 2.0.1 allows it to work without issue. Issue remains in Jumper 2.1.0 as well.
https://kubadownload.com/news/quickcc-tweak

Iphone 11,8 IOS 12.4

**Comment by neoighodaro** [comment]
Probably an issue with flipswitch
