### ISSUE TITLE
 iPad OS 13.3.1 - Landscape issue and Settings Issue

### ISSUE THREAD

**Issue by girron** [neoighodaro/switcher-issues#3]
The custom URL scheme menu appears in portrait mode. When i rotate the device, the switcher bar then disappears. Also the size of the tab does not resize. 

When I go to make a custom task and then delete, Settings freezes and I am forced to close out and re-open.

**Comment by neoighodaro** [comment]
Hey

Can you send me a screen recording



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by girron** [comment]
I’m trying to attach a screen recording. Not sure if it is working.
![animated](https://user-images.githubusercontent.com/3522893/78093827-e94ae400-7387-11ea-89cb-e379d8df3b4e.gif)

**Comment by girron** [comment]
I also just noticed that after updating switcher this morning, the custom URLs don’t even show.
![IMG_0036](https://user-images.githubusercontent.com/3522893/78151766-c81cde80-73ed-11ea-8aeb-536e2119d119.png)

**Comment by neoighodaro** [comment]
Try again, should be fixed now.
