### ISSUE TITLE
iOS 13.5 support?

### ISSUE THREAD

**Issue by njb113** [neoighodaro/switcher-issues#4]
Bought Jumper on my iPhone 11 Pro Max running iOS 13.5 and having issues getting it to work. Any help is appreciated!

**Comment by neoighodaro** [comment]
Hey, add ryan petrichs repo and download flipswitch and rocketbootstrap from there



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by Jayfinesse25** [comment]
Hey I brought switcher but I can’t add any apps onto it I can only use the slider for my recent apps. It says none whenever I try to add a app as if I have no apps. Help plz

**Comment by neoighodaro** [comment]
Download the latest applist from Ryan Petrich's repo https://rpetri.ch/repo



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by Jayfinesse25** [comment]
I have it downloaded already

**Comment by neoighodaro** [comment]
And you still can't see your applications list??

What phone, firmware, version of Switcher and version of applist?



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by Jayfinesse25** [comment]
I have an iPhone 11, iOS 13.5, version 1.5.16 of Applist and version 1.1.5
of switcher

**Comment by neoighodaro** [comment]
I use similar. So either it clashes with one of your tweaks or something. But I can confirm it works just fine. I don't know how else I can help.

If you can't get it to work, you can request a refund.



Neo Ighodaro
Software Engineer | Twitter | neoighodaro.com

**Comment by Jayfinesse25** [comment]
Ok yeah I understand thx I’ll see if I can figure it out I won’t refund
atleast i can use recent apps thx for the help.
