### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by Bo0sted** [neoighodaro/switcher-issues#7]
![image](https://user-images.githubusercontent.com/43390612/212766492-b4e7fa6d-341c-4b94-b045-904d276959e9.png)

**Comment by neoighodaro** [comment]
Hello what iOS version are you on

**Comment by Bo0sted** [comment]
> Hello what iOS version are you on

14.4

**Comment by Bo0sted** [comment]
I'm still having the issue

**Comment by WCHighfill** [comment]
![F596923E-760B-4715-B6E0-2B704C505EDC](https://user-images.githubusercontent.com/26910562/230789019-8c9592dd-37ef-4cbd-8828-7bec4daa2c3b.jpeg)
Same issue here too. If I install LibTapSharp through deb it’s fine but don’t let me uninstall anything even if it doesn’t use LibTapSharp.
iPhone 11 on 14.3 Taurine
